### PR TITLE
Added Zstd Support

### PR DESCRIPTION
**Pull request by ldsands**
I've added the changes that I think are needed to support parquet files that were compressed with Zstd. I have very little experience with git and GitHub and programming in general please let me know what I did wrong (if anything) and be patient with me as you go over that.

### CODE REVIEW

**Comment by davidanthoff** [comment]
Awesome! I think the tests currently fail because our example dataset doesn't contain the zstd compressed files that you are trying to read during the tests. Maybe there is an updated test dataset that includes such files?

**Comment by ldsands** [comment]
I can convert the test dataset but I don't know where to download it, or then where to upload it. Again I'm not very familiar with GitHub and until now I did not know what Travis-CI until today.

**Comment by davidanthoff** [comment]
So I think the tests in this package use the test dataset from https://github.com/Parquet/parquet-compatibility, which seems way, way old and unmaintained and doesn't have any zstd files in it. I'm not sure what the right strategy at this point is to get the tests to work...

**Comment by ldsands** [comment]
Here are a couple of options.

1. We fork the repository you've been using add a zstd parquet file and call it done. (I've looked through all the forks and none of them are better maintained for what you use it for)
1. We transfer to using a different parquet repository that is better maintained (below are a few options that might work that I found they would all have to add zstd unfortunatly)
    - [Option 1](https://github.com/apache/parquet-testing)
    - [Option 2](https://github.com/dask/parquet-integration)
    - [Option 3](https://github.com/lightcopy/parquet-datasets)
1. We make another from scratch or fork any of the above and maintain our own (I would be willing to do this). This way we can have more updated parquet formats and add any other formats we want.
    - I may try doing this anyway I'll let you know if I do end up with something that might work better.

Any other ideas or do one of these sound good?

**Comment by ldsands** [comment]
Okay since I was waiting to transfer 700 gigs [I forked the parquet repository](https://github.com/ldsands/parquet-compatibility) for testing and created several for testing. Let me know what you think.

**Comment by davidanthoff** [comment]
@tanmaykm what is your take? I'm not familiar enough with the package to really have an opinion.

**Comment by tanmaykm** [comment]
The updated parquet-compatibility repo looks good. Thanks @ldsands! Tests should probably point to that now.

Also, would it be better to have [parquet-compatibility](https://github.com/ldsands/parquet-compatibility) under JuliaIO org? @ldsands & @davidanthoff ?

**Comment by davidanthoff** [comment]
> Also, would it be better to have parquet-compatibility under JuliaIO org?

Probably?

**Comment by ldsands** [comment]
Sounds good to me.

**Comment by tanmaykm** [comment]
I have forked parquet-compatibility from @ldsands at https://github.com/JuliaIO/parquet-compatibility now. Tests should pass once this PR is updated to work with that. Thanks!

**Comment by ldsands** [comment]
Okay, I took a stab at changing the test files.

**Comment by ldsands** [comment]
Oops, I'm still new to all of this I'll try to make sure I don't make another change until I've gotten it to work.

**Comment by ldsands** [comment]
I think I've hit a wall. I can't seem to figure out what some of this code does and I have no idea what to do about it. There are two Issues that seem to occur.

1. For the nation data where there is no compression there is a "x not defined" error from line 252 in curser.jl I cannot figure out what that code is doing.
1. the map_dict_vals from reader.jl seems to have issues when testing the no compression customers data. It says "ERROR: LoadError: BoundsError: attempt to access 48128-element Array{Array{UInt8,1},1} at index [48129]" I've tried to modify the line from the reader.jl that causes this and it didn't help so I'm out of my depth here.

All of the other parquet files go through the tests just fine so it is mostly working.

Also, I changed the parquet compatibility files I made in error in writeing them I've created a pull request for that repository that will fix the issues there. I'm getting better about testing before I make pull requests I didn't know about seperate branches until just the past few days that obviously helps with testing stuff.

Thoughts?

**Comment by tanmaykm** [comment]
Thanks for the update @ldsands. Will take a deeper look at this later today.

**Comment by tanmaykm** [comment]
I was able to reproduce it. Looks like we may be hitting a bug here. Will try and track it down.

**Comment by tanmaykm** [comment]
I dug a bit deeper, and I am not sure if there's an error in the test data, only the `*customer.parquet` files.

It looks like there's a page with dictionary data where the dictionary encodes only 48128 string/bytearray values while the data page has values in the range 0:65467. The data belongs to the `name` column of customer table.

@ldsands could you cross check the data once?

**Comment by ldsands** [comment]
I'm not entirely sure how this fixed it but I converted the original data from having a delimiter of "|" to a normal csv that seems to have fixed that issue (I did this just to look at the raw data and see if there was something in the original data causing the issue). Unfortunately, now there is another issue. I'll take a look at it and see if I can't figure it out.

**Comment by tclements** [comment]
This is the same error as #38 and #27 happening on different files.

**Comment by ldsands** [comment]
I'm sorry but I have not been able to figure this out. I'll be away from my computer this weekend so I will not be able to look at it again on Monday at the earliest. I don't think I'm going to be able to figure this out however it seems beyond my capabilities.

**Comment by tanmaykm** [comment]
I think I have narrowed this down to a bug in RLE/bit-packing hybrid reading. Will push a fix in a bit.

**Comment by tanmaykm** [comment]
That should be fixed by #42.
@ldsands could you rebase this PR and check?

**Comment by ldsands** [comment]
I think that fixed the issue. Unfortunately, I still come across three other errors when I try testing it all.

The first is testing hte schema. Here is the error:

```log
ERROR: LoadError: LoadError: MethodError: no method matching test_schema(::String)
```

The next is from line 18 in the test_cursors.jl file. Here is the error:

```log
ERROR: LoadError: LoadError: BoundsError: attempt to access Int64 at index [2]
```

The last error is also from test_cursors.jl. Here is the error:

```log
ERROR: LoadError: LoadError: MethodError: no method matching test_juliabuilder_row_cursor(::String)
```

When I commented out those two lines testing those functions, the testing worked so I think we almost have it.

Again, I've experimented with them both but I do not know what to do about them. Could you look into them @tanmaykm?

**Comment by xiaodaigh** [comment]
I have seen enough to be fairly confident that zstd (or any other compression supported by Julia can be added). Watch this space.

**Comment by xiaodaigh** [comment]
@ldsands 

Hey, Zstd is working in [Diban.jl](https://github.com/xiaodaigh/Diban.jl). I am working (slowly) to try and get this back into Parquet.jl.

But it was a simple addition. If you can't wait just try Diban.jl


```julia
]activate diban-test
]dev Thrift

# add a particular version of Parquet.jl with fixes
]add https://github.com/xiaodaigh/Parquet.jl#zj/fix-reader

# add the latest version of Dìbǎn
]add https://github.com/xiaodaigh/Diban.jl
````

And read your ZSTD compressed file using 

```julia
read_parquet(path_to_file)
````

**Comment by ldsands** [comment]
@xiaodaigh The issue wasn't the zstd. I didn't have difficulties with implimenting the zstd into the code even with my lack of experience. Instead it was the reading of the pyarrow created parquet files (newer version of parquet I assume) that are causing the issues. It seems that your [Diban.jl](https://github.com/xiaodaigh/Diban.jl) deals with those issues. I'll have to try it out. Good luck with moving everything back into Parquet.jl!

**Pull request closed without merging**
